# Generated by Django 4.1.1 on 2022-09-27 10:26

import datetime
from django.db import migrations, models
import job_portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=250)),
                ("address", models.CharField(max_length=500)),
                (
                    "apply_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "resume",
                    models.FileField(
                        null=True, upload_to=job_portal.models.Applicant.nameFile
                    ),
                ),
                ("is_selected", models.BooleanField(default=False)),
            ],
        ),
    ]
